language: node_js
before_install:
  - nvm install stable
  - node -v
  - npm -v
  - npm install -g gulp
  - npm install gulp
  - npm install gulp-typescript
deploy:
  provider: npm
  email: npm@smart-coordination.com
  api_key:
    secure: MWmhzp2ApCHjUcrPsOvh12cgioSI021vbpJWIuEelyPMRwee9uwHDsD75JLFFK8gnV3pvo/686tcvGshiPwJU7Am1tU9oqPHbHYfW4EnMTeD4vsyCPr8MEDrh/ekZAmDqiGNLtPtPX97DS719du83llgLsiTnjuhKGvNfQJGFIzfLKjTS/WGX/LS+ZN5cmmxmqcot10ztyvXLSGRjh+ZFsAUnJiapTciJcvnoLt2nQrAvaT0lythgT2iCWfIbK3Cc+oAUkqU703KdSRUP5qsowoF2/v2e1DhdUqel19ElbkFCMBTe/DEZUBC9J9MKAqdRAraYH2XB6476ou5hpsBdpzk2e036y4CS1bqKG64GNXQZZal5dn2+p1PgwW63BQVAvVK3kENpYvmNprT4IfA0A8eYuHYi6QcGufnpSw5MnETZWsW5044L9OZ/0zkCCu3eaa4nftOKld/oQMGw+T6fkawPgnVrAa30r8XC4E1oxnTa1H4rgI9YZj0XJ0WnuFJ3VFxdqhe7aK9GKyW/iuaJZmYrwL9gLneHGhP02HhDX5FFeIpMd+77Vg49fMnhHW7TnQQxwS0f7ZMyW1YbBT/lDOVFv1ReruzhR2HJqkzdP+rBTROmXOjM+WM8nlMiLDLVC+vWqlFXifQ5fF8dIXQdkiboLm2yV+SLz66Zxk2tWY=
  on:
    tags: true
    repo: pushrocks/gulp-makejson
notifications:
  slack:
    secure: oM8yCioyO48J/6mLxZxn6UhGw0AcV6FJbPoSUfrXtFIB6/CyuUROoUx4KbDyaECzQfmPcISfms5q8KV3a9/k3qZNAK4HFD8Jbd0Hk1e/XdMJNQ8skF1pOiK/LKnydBaULx4EtXUaPx0d75V9+gvYZmQOJHUbeQci1Xl45zJGW8kQqxDLA3GnW/BzcxIIqexmtLTi6Aw0YpYOfv+pjgHovUuzeVG/y/5B46YCui/3N+Og+i4Ka8pU84c0B/D5O3PqfwfwD3RU5dwdLp+8xCF+HgW6X1dXKbH7EWJUG62MHTMAvmr20+rUGGNIoX2mZyrtnDvayFh4LjbSR5ifMUpl8DXDOF2iGoyTd+97KGtMJNEvmkQdN/44m5Vd+ov+kNOOx5ZldmcGWBZwi8dGigAZ3h1q9FVqfKsd3ZtRgCvikMwFhbXLipeuTKRpNC35Zg6Fdi56UfI36ueR59Aa0CCB54QRcrZqaiG7xNU7vjWbqUJAuFwXH7JtGvZRVhrW2nGXBQ/x7tsCkdol4Ci+wXXXmb8nB3UtjqoCQITjs4chHuP//Fv+KDL9IhEsNNF8czrs3BKbcITBuIcEE1VgXfoMdO8LzcFFwWJOQ8J7d68Dll+3mth/8jmwTt2kxX1Gbin5NzeYKLz0OP9I3aBhhTX6VrKbcbdUHX3kqay8BTl9Q+s=
